[[redirects]]
  from = "/fleet"
  to = "/fleet.html"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 301

[build.processing.html]
  pretty_urls = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.css]
  bundle = false
  minify = false
